apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: "32.1.0"
      helm:
        values: |
          deployment:
            replicas: 3
          service:
            type: LoadBalancer
          ports:
            web:
              exposedPort: 80
            websecure:
              exposedPort: 443
              tls:
                enabled: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"