apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base
  - ingress.yaml
  - middleware-default-headers.yaml

patches:
  - path: helm-values-patch.yaml