apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - ../../base
  - certificate.yaml
  - ingress-external.yaml
  - ingress-internal.yaml

patches:
  - path: helm-values-patch.yaml