---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: vaultwarden-admin
  namespace: kube-system
spec:
  encryptedData:
    ADMIN_TOKEN: AgAzt800AwLtxd7S01VgiM/vWzDBqP+deYFfRG+/HW7f8ew90geNZCWXVw4+0dYZ1u1fpTKTZdH35fWyCTB3yG2KoJiox0izm51JSeTBky9SB9njQ+3vkfdAhFWkt9DlRTC/vQi1sc7OA89CXBiDEL7dtxHj+CLnirYty0y1g1XtasvFxfWJUEDYMBOMKfCNSFs8iSiCUmPRu3RsgZA2AodCKAeCBN+2ods+LeGFTLbLj0zYFpIzYTu5JDr2MWhhLMk322+ztkdVY1GrTksmITJ0lA13VCtkssGsC12EDIqjAa7J5pe9NcrmxFklIl/Ep8G1YeGLjHUQpjkS5m6J687sspUQ5UY7/dZF7glu1qySFd46ux/FlVO8ea36LHKFi8+Rw5UmYOrNaQlbxi5Txg28JwLi777BpfKXP1NYyf4y3bqTB2pq/irZtfTgHVMRhHBcwfAIcg92yxnL9Sw80mIuSgVIoXHtr/c8k7/Nw2GiB4KzoYKWo4YSRu4nzMJ3X0FMVi19mVNK3D16e5HExouGPe1FJybth1T7GQ3ZMLBta5Iml/CacKkEqrNpnmObvmMa/yHvC1Po9rXp/R6VlY33xnlN4ihY9SZh+T60CDH+W+GJffGI25t57Er/w1nKMyITnGyEqXQU9fyQBWnj6Ci3mwqfRx0kAM3UPlTrHAgBRP4W38Q+b4NVH4sE2m/AjAVFXsqVpa9jIX0/Xvqi9vpTkjc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: vaultwarden-admin
      namespace: vaultwarden
    type: Opaque